version: 'python:3.10-slim'

services:
  quantspica:
    build: .
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
    volumes:
      - .:/app
    command: python main.py
